### ISSUE TITLE
Forge Compatibility

### ISSUE THREAD

**Issue by FwoofyBoi** [JustAHuman-xD/MoreCobblemonTweaks#2]
We are on forge and many of our players have wanted these features for a while, but sadly there is no forge versions of the mod. Thank you!

**Comment by JustAHuman-xD** [comment]
Just a Heads up, this may have to wait until cobblemon switches to neoforge, as some of the stuff I do with mixins I can't do with forge mixins but I can do with neoforge.

I still *may* try and port it for the 1.20.1 version but no guarantees as it's not my top priority atm

**Comment by JustAHuman-xD** [comment]
Until I make an official forge port you could try using: https://www.curseforge.com/minecraft/mc-mods/sinytra-connector

**Comment by FwoofyBoi** [comment]
Are the mods needed both client and server side? Or just client?

**Comment by JustAHuman-xD** [comment]
> Are the mods needed both client and server side? Or just client?

Well MoreCobblemonTweaks is client sided so I assume only client, but I've never tried connector so no clue, I just know of it's existence

**Comment by FwoofyBoi** [comment]
Thank you, ill look into it. We will probably be updating to fabric
eventually anyways. I appreciate the assistance

**Comment by JustAHuman-xD** [comment]
An official neoforge port is coming in the update to Cobblemon 1.6 !

**Comment by JustAHuman-xD** [comment]
And my neoforge port is out with 1.0.0 !
