### ISSUE TITLE
Support Cobbreeding

### ISSUE THREAD

**Issue by Ali-Suarez** [JustAHuman-xD/MoreCobblemonTweaks#3]
Well, I see "MoreCobblemonTweaks" adds lore to egg but I can't seem to find it in this server that uses cobbreeding, it does even have a diff tag from the screenshot in the mod. In the mod gallery at modrinth it says: "cobblemon:pokemon_egg" and mine says "cobbreeding:pokemon_egg". Thanks!

**Comment by JustAHuman-xD** [comment]
Implemented in v0.6.0 !
