### ISSUE TITLE
Crash issue

### ISSUE THREAD

**Issue by VOrlando520** [JustAHuman-xD/MoreCobblemonTweaks#5]
Is causing people to lose pokemon put in their pc while they crash from what looks like an issue from this mod.
Screenshot from a player who got a crash report for me
![IMG_5864](https://github.com/user-attachments/assets/8627a475-6cdd-43d9-9cf6-9c7c4ed11705)

**Comment by JustAHuman-xD** [comment]
I will take a look! Not sure how they could be loosing pokemon though since it's on the client not server 🤔

**Comment by VOrlando520** [comment]
Crashes mid transfer, so guessing it cant write to the server files when moving pokemon back and forth.

**Comment by JustAHuman-xD** [comment]
Alright think I've got it figured out

**Comment by JustAHuman-xD** [comment]
Can't test it right now as I'm in class but once I do and confirm it works I'll push out the update, I've got some other features ready anyway hah

**Comment by JustAHuman-xD** [comment]
Did not mean to close it yet hah

**Comment by JustAHuman-xD** [comment]
Fixed in release https://github.com/JustAHuman-xD/MoreCobblemonTweaks/commit/0e593cd365cdb4f190a2af1fe1090ac25137ab54
