### ISSUE TITLE
Incorrect Tooltip

### ISSUE THREAD

**Issue by Ghostyxs** [JustAHuman-xD/MoreCobblemonTweaks#6]
![Capture](https://github.com/user-attachments/assets/0273db1e-a520-41d9-b181-975a236943d2)
Format of the tooltip is completely different then shown in the features list. 

I have the minimum required mods to run this mod to make sure it wasnt anything else causing it :)
architectury API
Cobblemon
Cobbreeding 
Fabric API
MoreCobblemonTweaks

Edit: i tried adding cloth config api since it was listed as a optional dependency, but it still displayed the same

**Comment by JustAHuman-xD** [comment]
oh crap! that's a big issue hah, I will tackle this right now!

**Comment by JustAHuman-xD** [comment]
(forgot to update this, fixed in v0.7.1)
